# Generated by Django 5.0.14 on 2026-06-15 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GooglePlacesData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('google_place_id', models.CharField(blank=True, max_length=255)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('star_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('review_velocity_30d', models.FloatField(blank=True, null=True)),
                ('phone_friction_count', models.IntegerField(default=0)),
                ('phone_friction_keywords', models.JSONField(blank=True, default=list)),
                ('opening_hours', models.JSONField(blank=True, null=True)),
                ('hours_changed', models.BooleanField(default=False)),
                ('hours_change_type', models.CharField(blank=True, max_length=20, null=True)),
                ('response_rate', models.FloatField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_places_data', to='core.practice')),
            ],
            options={
                'db_table': 'google_places_data',
                'indexes': [models.Index(fields=['practice', 'collected_at'], name='google_plac_practic_c0390e_idx')],
            },
        ),
    ]
