# Generated by Django 5.0.14 on 2026-06-14 16:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SovaConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('thread_id', models.CharField(max_length=255, unique=True)),
                ('user_identifier', models.CharField(max_length=255)),
                ('messages', models.JSONField(default=list)),
                ('mode', models.CharField(default='chatbot', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sova_conversations',
            },
        ),
        migrations.CreateModel(
            name='SovaTaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('task_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('progress', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_runs', to='orchestrator.sovaconversation')),
            ],
            options={
                'db_table': 'sova_task_runs',
            },
        ),
    ]
