# Generated by Django 5.0.14 on 2026-06-14 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('npi', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('practice_name', models.CharField(max_length=255)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('specialty_taxonomy_code', models.CharField(blank=True, max_length=20)),
                ('specialty_display', models.CharField(blank=True, max_length=100)),
                ('practice_type', models.CharField(blank=True, max_length=20)),
                ('entity_type', models.CharField(blank=True, max_length=20)),
                ('website_url', models.CharField(blank=True, max_length=500)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_current_client', models.BooleanField(default=False)),
                ('is_oig_excluded', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'practices',
                'indexes': [models.Index(fields=['state'], name='practices_state_29159e_idx'), models.Index(fields=['zip_code'], name='practices_zip_cod_bb849c_idx'), models.Index(fields=['specialty_taxonomy_code'], name='practices_special_5a65a1_idx'), models.Index(fields=['is_active'], name='practices_is_acti_5d146c_idx'), models.Index(fields=['practice_type'], name='practices_practic_550199_idx'), models.Index(fields=['state', 'is_active'], name='practices_state_aace20_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubFragmentRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('last_run_at', models.DateTimeField(null=True)),
                ('last_run_status', models.CharField(default='never_run', max_length=20)),
                ('records_written', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('expected_interval_hours', models.IntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sub_fragment_run_log',
                'indexes': [models.Index(fields=['name'], name='sub_fragmen_name_1ba8cb_idx'), models.Index(fields=['last_run_status'], name='sub_fragmen_last_ru_4adf74_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeadScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('composite_score', models.FloatField()),
                ('fit_score', models.FloatField(blank=True, null=True)),
                ('operational_pain_score', models.FloatField(blank=True, null=True)),
                ('timing_score', models.FloatField(blank=True, null=True)),
                ('first_party_intent_score', models.FloatField(blank=True, null=True)),
                ('technographic_score', models.FloatField(blank=True, null=True)),
                ('human_route_score', models.FloatField(blank=True, null=True)),
                ('geography_score', models.FloatField(blank=True, null=True)),
                ('tier', models.CharField(max_length=10)),
                ('modifiers_applied', models.JSONField(default=list)),
                ('signals_summary', models.JSONField(default=dict)),
                ('hot_qualification', models.JSONField(default=dict)),
                ('scored_at', models.DateTimeField(db_index=True)),
                ('is_latest', models.BooleanField(default=True)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_scores', to='core.practice')),
            ],
            options={
                'db_table': 'lead_scores',
                'indexes': [models.Index(fields=['practice', 'is_latest'], name='lead_scores_practic_b54f0f_idx'), models.Index(fields=['tier', 'is_latest'], name='lead_scores_tier_b0340a_idx'), models.Index(fields=['scored_at'], name='lead_scores_scored__ba2ebf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('signal_type', models.CharField(db_index=True, max_length=50)),
                ('signal_source', models.CharField(max_length=50)),
                ('raw_value', models.FloatField()),
                ('confidence', models.CharField(max_length=10)),
                ('evidence_count', models.IntegerField(default=1)),
                ('evidence_summary', models.TextField(blank=True)),
                ('half_life_days', models.IntegerField()),
                ('collected_at', models.DateTimeField(db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='core.practice')),
            ],
            options={
                'db_table': 'signals',
                'indexes': [models.Index(fields=['practice', 'signal_type', 'collected_at'], name='signals_practic_f8a211_idx')],
            },
        ),
    ]
